//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5.Employee__LINQtoENTITIES_
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUST_ID { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_CITY { get; set; }
        public string AGENT_CODE { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
    
        public virtual AGENT AGENT { get; set; }
        public virtual Order Order { get; set; }
    }
}
