//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5.Employee__LINQtoENTITIES_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<int> Emp_Age { get; set; }
        public string Emp_Email { get; set; }
        public Nullable<System.DateTime> Emp_DateofJoining { get; set; }
    }
}
