//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5.Employee__LINQtoENTITIES_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_No { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
