//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5.Employee__LINQtoENTITIES_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int movie_Id { get; set; }
        public string actor_Id { get; set; }
        public string movie_Name { get; set; }
        public string movie_Year { get; set; }
    
        public virtual Actor Actor { get; set; }
    }
}
