<?xml version="1.0" encoding="utf-8"?><Database Name="NCS2020" Class="NCS2020_DeptDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=NCS2020;Integrated Security=True" SettingsObjectName="Q4___Department_Table__CRUD_.Properties.Settings" SettingsPropertyName="NCS2020ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="Dept_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dept_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>